version: "3"
services:
  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - .env.test

  node_app_repo-provas-test:
    container_name: node_app_repo-provas-test
    build: .
    env_file:
      - .env.test
    depends_on:
      - db
